In [2]:
import numpy as np

In [5]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
a.shape

(12,)

In [7]:
a.shape = (3,4)

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
a[2]

array([ 8,  9, 10, 11])

In [12]:
a[2,1]

9

In [13]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [14]:
from collections import deque

In [49]:
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
dq.appendleft(-1)
dq

deque([-1, 0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
dq.rotate(3)
dq

deque([4, 5, 6, 7, 8, 9, 0, 1, 2, 3])

In [28]:
dq.pop()

4

In [29]:
dq

deque([0, 1, 2, 3])